name: vocatio
description: "Vocatio is a multiplatform app for university attendance tracking. It replaces oral attendance with dynamic QR codes, geolocation, and biometric authentication, reducing class time, preventing unfair absences, and generating automatic reports for students and faculty."
publish_to: 'none'
version: 1.0.3-alpha.1+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  device_preview: ^1.3.1
  provider: ^6.1.5
  flutter_platform_widgets: ^9.0.0
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/images/logo_vocatio_transparente.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_vocatio_ios.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_vocatio_pequena_transparente.png"
  
  web: 
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"
  macos:
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"
  windows:
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"
  linux:
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"


flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/images/logo_vocatio_pequena_transparente.png 
  