name: vocattio
description: "Vocattio is a multiplatform app for university attendance tracking. It replaces oral attendance with dynamic QR codes, geolocation, and biometric authentication, reducing class time, preventing unfair absences, and generating automatic reports for students and faculty."
publish_to: 'none'
version: 1.3.0-alpha.1+6

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  device_preview: ^1.3.1
  provider: ^6.1.5
  flutter_platform_widgets: ^9.0.0
  path_provider: ^2.1.5
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  camera: ^0.10.5+2
  path: ^1.9.0
  mobile_scanner: ^6.0.2
  geolocator: ^14.0.2
  permission_handler: ^11.3.1
  http: ^1.5.0
  flutter_dotenv: ^6.0.0
  get_it: ^8.2.0
  web: ^1.1.1
  bson: ^5.0.7
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/images/
   - .env
   - assets/audios/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo_vocatio_ios.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_vocatio_pequena_transparente.png"
  
  web: 
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"
  macos:
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"
  windows:
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"
  linux:
    generate: true
    image_path: "assets/images/logo_vocatio_pequena_transparente.png"


flutter_native_splash:
  color: "#FFFFFF" 
  image: assets/images/logo_vocatio_pequena_transparente.png 

  color_dark: "#000000"  
  image_dark: assets/images/logo_vocatio_pequena_transparente.png 
  
