name: vocatio
description: "Vocatio is a multiplatform app for university attendance tracking. It replaces oral attendance with dynamic QR codes, geolocation, and biometric authentication, reducing class time, preventing unfair absences, and generating automatic reports for students and faculty."
publish_to: 'none'
version: 1.0.1-alpha.1+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2
  device_preview: ^1.3.1
  provider: ^6.1.5
  flutter_platform_widgets: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
   - assets/images/logo_vocatio_transparente.png
