// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJguncNOdNHKUkOJjw2pCQ2QFKnc1__T4',
    appId: '1:198635508987:web:91fe8f6344cdf405f30c5e',
    messagingSenderId: '198635508987',
    projectId: 'vocattio-f4c99',
    authDomain: 'vocattio-f4c99.firebaseapp.com',
    storageBucket: 'vocattio-f4c99.firebasestorage.app',
    measurementId: 'G-QFRZKY8FMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-ZVpyWRGei13f_kDDfJLuoc66l691UpQ',
    appId: '1:198635508987:android:482d2cded8b124d6f30c5e',
    messagingSenderId: '198635508987',
    projectId: 'vocattio-f4c99',
    storageBucket: 'vocattio-f4c99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt1ubOBay6SA0A68kQGb0QmIvVoX_ltGo',
    appId: '1:198635508987:ios:c1af13cc5aea39f4f30c5e',
    messagingSenderId: '198635508987',
    projectId: 'vocattio-f4c99',
    storageBucket: 'vocattio-f4c99.firebasestorage.app',
    iosBundleId: 'com.example.vocatio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt1ubOBay6SA0A68kQGb0QmIvVoX_ltGo',
    appId: '1:198635508987:ios:c1af13cc5aea39f4f30c5e',
    messagingSenderId: '198635508987',
    projectId: 'vocattio-f4c99',
    storageBucket: 'vocattio-f4c99.firebasestorage.app',
    iosBundleId: 'com.example.vocatio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJguncNOdNHKUkOJjw2pCQ2QFKnc1__T4',
    appId: '1:198635508987:web:2f9831823bccdf57f30c5e',
    messagingSenderId: '198635508987',
    projectId: 'vocattio-f4c99',
    authDomain: 'vocattio-f4c99.firebaseapp.com',
    storageBucket: 'vocattio-f4c99.firebasestorage.app',
    measurementId: 'G-P7FLTRC6KS',
  );

}