# Desativa todos os logs INFO e abaixo
org.slf4j.simpleLogger.defaultLogLevel=error

# Opcional: desativa também logs de inicialização
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
