name: Flutter Build

on:
  push:
    branches:
      - main
    paths:
      - "app/vocatio/**"

jobs:
  build:
    if: github.actor != 'github-actions[bot]'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Install dependencies
        working-directory: app/vocatio
        run: flutter pub get

      - name: Get current build number
        working-directory: app/vocatio
        id: build_number
        run: |
          CURRENT=$(grep '^version:' pubspec.yaml | cut -d'+' -f2)
          if [ -z "$CURRENT" ]; then
            BUILD_NUMBER=1
          else
            BUILD_NUMBER=$((CURRENT + 1))
          fi
          echo "BUILD_NUMBER=$BUILD_NUMBER" >> $GITHUB_ENV
          echo "New build number: $BUILD_NUMBER"

      - name: Update pubspec.yaml
        working-directory: app/vocatio
        run: |
          VERSION_BASE=$(grep '^version:' pubspec.yaml | cut -d'+' -f1)
          sed -i "s/^version:.*/${VERSION_BASE}+$BUILD_NUMBER/" pubspec.yaml
          echo "Updated version line:"
          grep '^version:' pubspec.yaml

      - name: Commit updated pubspec.yaml
        working-directory: app/vocatio
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add pubspec.yaml
          git commit -m "chore: update build number to $BUILD_NUMBER"
          cd ../..
          git push origin main

      - name: Display build result
        run: echo "Build #$BUILD_NUMBER successfully registered and committed!"
